static_site_generator: custom

build:
  install: npm install
  command: npm run docs:build
  output: docs/.vitepress/dist

collections:
  wiki:
    output: true
    folder: docs/wiki
    label: Wiki
    editor:
      type: markdown
